
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiceBus.EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class Address
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Address()
    {

        this.Orders = new HashSet<Order>();

    }


    public int Id { get; set; }

    public string PostCode { get; set; }

    public int HouseNumber { get; set; }

    public string HouseNumberExtension { get; set; }

    public string Street { get; set; }

    public string District { get; set; }

    public string DoorNumber { get; set; }

    public string City { get; set; }



    public virtual BillingInformation BillingInformation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Order> Orders { get; set; }

    public virtual Storage Storage { get; set; }

}

}
