
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiceBus.EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int Id { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<System.DateTime> DeliveryDate { get; set; }

    public Nullable<int> AddressId { get; set; }

    public Nullable<int> BillingInformationId { get; set; }

    public Nullable<int> UserId { get; set; }

    public string InvoiceNr { get; set; }

    public int OrderStatusId { get; set; }

    public string CustNotes { get; set; }



    public virtual Address Address { get; set; }

    public virtual BillingInformation BillingInformation { get; set; }

    public virtual Basket Basket { get; set; }

    public virtual User User { get; set; }

    public virtual OrderStatus OrderStatus { get; set; }

}

}
