
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ServiceBus.EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public System.Guid Id { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<System.DateTime> DeliveryDate { get; set; }

    public Nullable<System.Guid> AddressId { get; set; }

    public Nullable<System.Guid> BillingInformationId { get; set; }

    public Nullable<System.Guid> UserId { get; set; }

    public string InvoiceNr { get; set; }

    public System.Guid OrderStatusId { get; set; }

    public string CustNotes { get; set; }

    public string OrderNumber { get; set; }

    public System.Guid Basket_Id { get; set; }



    public virtual Address Address { get; set; }

    public virtual BillingInformation BillingInformation { get; set; }

    public virtual Basket Basket { get; set; }

    public virtual User User { get; set; }

    public virtual OrderStatus OrderStatus { get; set; }

}

}
