//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentControl.ServiceZETRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentControl.ServiceZETRef.PluralizedOfStudentgUMYyf5D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentControl.ServiceZETRef.Students))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentControl.ServiceZETRef.Student))]
    public partial class DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentControl.ServiceZETRef.Result ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentControl.ServiceZETRef.Result Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentControl.ServiceZETRef.ResultType ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentControl.ServiceZETRef.ResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PluralizedOfStudentgUMYyf5D", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StudentControl.ServiceZETRef.Students))]
    public partial class PluralizedOfStudentgUMYyf5D : StudentControl.ServiceZETRef.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudentControl.ServiceZETRef.Student[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentControl.ServiceZETRef.Student[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Students", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Students : StudentControl.ServiceZETRef.PluralizedOfStudentgUMYyf5D {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Student : StudentControl.ServiceZETRef.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.Enums")]
    public enum ResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceZETRef.IZET006Service")]
    public interface IZET006Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetStudent", ReplyAction="http://tempuri.org/IZET006Service/GetStudentResponse")]
        StudentControl.ServiceZETRef.Student GetStudent(string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetStudent", ReplyAction="http://tempuri.org/IZET006Service/GetStudentResponse")]
        System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Student> GetStudentAsync(string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetAllStudents", ReplyAction="http://tempuri.org/IZET006Service/GetAllStudentsResponse")]
        StudentControl.ServiceZETRef.Students GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetAllStudents", ReplyAction="http://tempuri.org/IZET006Service/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Students> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetAllStudentsSortedBySurname", ReplyAction="http://tempuri.org/IZET006Service/GetAllStudentsSortedBySurnameResponse")]
        StudentControl.ServiceZETRef.Students GetAllStudentsSortedBySurname();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetAllStudentsSortedBySurname", ReplyAction="http://tempuri.org/IZET006Service/GetAllStudentsSortedBySurnameResponse")]
        System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Students> GetAllStudentsSortedBySurnameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetStudentsByCity", ReplyAction="http://tempuri.org/IZET006Service/GetStudentsByCityResponse")]
        StudentControl.ServiceZETRef.Students GetStudentsByCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/GetStudentsByCity", ReplyAction="http://tempuri.org/IZET006Service/GetStudentsByCityResponse")]
        System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Students> GetStudentsByCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/SendStudentsByEmail", ReplyAction="http://tempuri.org/IZET006Service/SendStudentsByEmailResponse")]
        StudentControl.ServiceZETRef.Result SendStudentsByEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/SendStudentsByEmail", ReplyAction="http://tempuri.org/IZET006Service/SendStudentsByEmailResponse")]
        System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Result> SendStudentsByEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/CreateHtmlDocument", ReplyAction="http://tempuri.org/IZET006Service/CreateHtmlDocumentResponse")]
        StudentControl.ServiceZETRef.Result CreateHtmlDocument(string filePath, StudentControl.ServiceZETRef.Student[] studentsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZET006Service/CreateHtmlDocument", ReplyAction="http://tempuri.org/IZET006Service/CreateHtmlDocumentResponse")]
        System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Result> CreateHtmlDocumentAsync(string filePath, StudentControl.ServiceZETRef.Student[] studentsList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZET006ServiceChannel : StudentControl.ServiceZETRef.IZET006Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZET006ServiceClient : System.ServiceModel.ClientBase<StudentControl.ServiceZETRef.IZET006Service>, StudentControl.ServiceZETRef.IZET006Service {
        
        public ZET006ServiceClient() {
        }
        
        public ZET006ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZET006ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZET006ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZET006ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentControl.ServiceZETRef.Student GetStudent(string studentID) {
            return base.Channel.GetStudent(studentID);
        }
        
        public System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Student> GetStudentAsync(string studentID) {
            return base.Channel.GetStudentAsync(studentID);
        }
        
        public StudentControl.ServiceZETRef.Students GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Students> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public StudentControl.ServiceZETRef.Students GetAllStudentsSortedBySurname() {
            return base.Channel.GetAllStudentsSortedBySurname();
        }
        
        public System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Students> GetAllStudentsSortedBySurnameAsync() {
            return base.Channel.GetAllStudentsSortedBySurnameAsync();
        }
        
        public StudentControl.ServiceZETRef.Students GetStudentsByCity(string city) {
            return base.Channel.GetStudentsByCity(city);
        }
        
        public System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Students> GetStudentsByCityAsync(string city) {
            return base.Channel.GetStudentsByCityAsync(city);
        }
        
        public StudentControl.ServiceZETRef.Result SendStudentsByEmail() {
            return base.Channel.SendStudentsByEmail();
        }
        
        public System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Result> SendStudentsByEmailAsync() {
            return base.Channel.SendStudentsByEmailAsync();
        }
        
        public StudentControl.ServiceZETRef.Result CreateHtmlDocument(string filePath, StudentControl.ServiceZETRef.Student[] studentsList) {
            return base.Channel.CreateHtmlDocument(filePath, studentsList);
        }
        
        public System.Threading.Tasks.Task<StudentControl.ServiceZETRef.Result> CreateHtmlDocumentAsync(string filePath, StudentControl.ServiceZETRef.Student[] studentsList) {
            return base.Channel.CreateHtmlDocumentAsync(filePath, studentsList);
        }
    }
}
