//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBusTests.CampaignService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceBusTests.CampaignService.PluralizedOfCampaigngUMYyf5D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceBusTests.CampaignService.Campaigns))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceBusTests.CampaignService.Campaign))]
    public partial class DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceBusTests.CampaignService.Result ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBusTests.CampaignService.Result Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceBusTests.CampaignService.ResultType ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBusTests.CampaignService.ResultType ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PluralizedOfCampaigngUMYyf5D", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceBusTests.CampaignService.Campaigns))]
    public partial class PluralizedOfCampaigngUMYyf5D : ServiceBusTests.CampaignService.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceBusTests.CampaignService.Campaign[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceBusTests.CampaignService.Campaign[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campaigns", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Campaigns : ServiceBusTests.CampaignService.PluralizedOfCampaigngUMYyf5D {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Campaign", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.DataContracts")]
    [System.SerializableAttribute()]
    public partial class Campaign : ServiceBusTests.CampaignService.DTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultType", Namespace="http://schemas.datacontract.org/2004/07/SharedLibs.Enums")]
    public enum ResultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CampaignService.ICampaignService")]
    public interface ICampaignService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/GetCampaign", ReplyAction="http://tempuri.org/ICampaignService/GetCampaignResponse")]
        ServiceBusTests.CampaignService.Campaign GetCampaign(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/GetCampaign", ReplyAction="http://tempuri.org/ICampaignService/GetCampaignResponse")]
        System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Campaign> GetCampaignAsync(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/GetAllCampaigns", ReplyAction="http://tempuri.org/ICampaignService/GetAllCampaignsResponse")]
        ServiceBusTests.CampaignService.Campaigns GetAllCampaigns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/GetAllCampaigns", ReplyAction="http://tempuri.org/ICampaignService/GetAllCampaignsResponse")]
        System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Campaigns> GetAllCampaignsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/AddCampaign", ReplyAction="http://tempuri.org/ICampaignService/AddCampaignResponse")]
        ServiceBusTests.CampaignService.Result AddCampaign(System.Guid guid, string name, double discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/AddCampaign", ReplyAction="http://tempuri.org/ICampaignService/AddCampaignResponse")]
        System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Result> AddCampaignAsync(System.Guid guid, string name, double discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/AddCampaignByObject", ReplyAction="http://tempuri.org/ICampaignService/AddCampaignByObjectResponse")]
        ServiceBusTests.CampaignService.Result AddCampaignByObject(ServiceBusTests.CampaignService.Campaign campaign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/AddCampaignByObject", ReplyAction="http://tempuri.org/ICampaignService/AddCampaignByObjectResponse")]
        System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Result> AddCampaignByObjectAsync(ServiceBusTests.CampaignService.Campaign campaign);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/EditCampaign", ReplyAction="http://tempuri.org/ICampaignService/EditCampaignResponse")]
        ServiceBusTests.CampaignService.Campaign EditCampaign(System.Guid guid, string name, double discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/EditCampaign", ReplyAction="http://tempuri.org/ICampaignService/EditCampaignResponse")]
        System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Campaign> EditCampaignAsync(System.Guid guid, string name, double discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/DeleteCampaign", ReplyAction="http://tempuri.org/ICampaignService/DeleteCampaignResponse")]
        ServiceBusTests.CampaignService.Result DeleteCampaign(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICampaignService/DeleteCampaign", ReplyAction="http://tempuri.org/ICampaignService/DeleteCampaignResponse")]
        System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Result> DeleteCampaignAsync(System.Guid guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICampaignServiceChannel : ServiceBusTests.CampaignService.ICampaignService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CampaignServiceClient : System.ServiceModel.ClientBase<ServiceBusTests.CampaignService.ICampaignService>, ServiceBusTests.CampaignService.ICampaignService {
        
        public CampaignServiceClient() {
        }
        
        public CampaignServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CampaignServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CampaignServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceBusTests.CampaignService.Campaign GetCampaign(System.Guid guid) {
            return base.Channel.GetCampaign(guid);
        }
        
        public System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Campaign> GetCampaignAsync(System.Guid guid) {
            return base.Channel.GetCampaignAsync(guid);
        }
        
        public ServiceBusTests.CampaignService.Campaigns GetAllCampaigns() {
            return base.Channel.GetAllCampaigns();
        }
        
        public System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Campaigns> GetAllCampaignsAsync() {
            return base.Channel.GetAllCampaignsAsync();
        }
        
        public ServiceBusTests.CampaignService.Result AddCampaign(System.Guid guid, string name, double discount) {
            return base.Channel.AddCampaign(guid, name, discount);
        }
        
        public System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Result> AddCampaignAsync(System.Guid guid, string name, double discount) {
            return base.Channel.AddCampaignAsync(guid, name, discount);
        }
        
        public ServiceBusTests.CampaignService.Result AddCampaignByObject(ServiceBusTests.CampaignService.Campaign campaign) {
            return base.Channel.AddCampaignByObject(campaign);
        }
        
        public System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Result> AddCampaignByObjectAsync(ServiceBusTests.CampaignService.Campaign campaign) {
            return base.Channel.AddCampaignByObjectAsync(campaign);
        }
        
        public ServiceBusTests.CampaignService.Campaign EditCampaign(System.Guid guid, string name, double discount) {
            return base.Channel.EditCampaign(guid, name, discount);
        }
        
        public System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Campaign> EditCampaignAsync(System.Guid guid, string name, double discount) {
            return base.Channel.EditCampaignAsync(guid, name, discount);
        }
        
        public ServiceBusTests.CampaignService.Result DeleteCampaign(System.Guid guid) {
            return base.Channel.DeleteCampaign(guid);
        }
        
        public System.Threading.Tasks.Task<ServiceBusTests.CampaignService.Result> DeleteCampaignAsync(System.Guid guid) {
            return base.Channel.DeleteCampaignAsync(guid);
        }
    }
}
